name: ktlint

on:
  pull_request:

jobs:
  ktlint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Run ktlint
      run: |
        cd nfts/mobile/android/MetakeepCodeSample
        ./gradlew ktlint

